baseURL: https://rarhomeinspections.com
languageCode: en-us
title: RAR Home Inspections
copyright: RAR of Texas 2022
paginate: 3
summaryLength: 40
googleAnalytics: G-6LX0S4DQ81

markup:
  goldmark:
    renderer:
      unsafe: true
      
params:
  favicon: /logo/RAR-HI_LOGO_SQUARE.svg
  brandlogo_dark: /logo/RAR-HI_LOGO_LONG.png
  description: RAR Home Inspections - Rosenberg, TX

  
menu:
    nav:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: schedule
      name: Schedule
      url: /schedule/
      weight: 2
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 3
    - identifier: Credentials
      name: Credentials
      url: /Credentials/
      weight: 4
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 5